-- Schema snapshot additions for session_entries cache exposure
alter table if exists public.session_entries
  add column if not exists created_at timestamptz not null default now();

grant usage on schema public to anon, authenticated;
grant select, insert, update on table public.session_entries to anon, authenticated;
grant select (created_at) on public.session_entries to anon, authenticated;

comment on table public.session_entries is 'expose for cache refresh';"\n-- Diamond Sports Book wallet and markets schema\ncreate table if not exists public.events (\n  id uuid primary key default gen_random_uuid(),\n  title text not null,\n  venue text,\n  starts_at timestamptz,\n  ends_at timestamptz,\n  status text not null default 'upcoming'\n);\n\ncreate table if not exists public.markets (\n  id uuid primary key default gen_random_uuid(),\n  event_id uuid not null references public.events(id) on delete cascade,\n  name text not null,\n  type text not null,\n  rake_bps int not null default 500,\n  status text not null default 'open',\n  closes_at timestamptz,\n  created_at timestamptz not null default now()\n);\n\ncreate table if not exists public.outcomes (\n  id uuid primary key default gen_random_uuid(),\n  market_id uuid not null references public.markets(id) on delete cascade,\n  label text not null,\n  sort_order int not null default 0\n);\n\ncreate table if not exists public.wallet_accounts (\n  user_id uuid primary key references auth.users(id) on delete cascade,\n  balance bigint not null default 0\n);\n\ncreate table if not exists public.wallet_transactions (\n  id uuid primary key default gen_random_uuid(),\n  user_id uuid not null references auth.users(id) on delete cascade,\n  kind text not null,\n  amount bigint not null,\n  meta jsonb,\n  created_at timestamptz not null default now()\n);\n\ncreate table if not exists public.wagers (\n  id uuid primary key default gen_random_uuid(),\n  user_id uuid not null references auth.users(id) on delete cascade,\n  market_id uuid not null references public.markets(id) on delete cascade,\n  outcome_id uuid not null references public.outcomes(id) on delete cascade,\n  stake bigint not null check (stake > 0),\n  placed_at timestamptz not null default now(),\n  status text not null default 'pending'\n);\n\ncreate table if not exists public.withdrawals (\n  id uuid primary key default gen_random_uuid(),\n  user_id uuid not null references auth.users(id) on delete cascade,\n  amount bigint not null check (amount > 0),\n  status text not null default 'queued',\n  created_at timestamptz not null default now()\n);\n\ncreate index if not exists markets_event_id_idx on public.markets (event_id);\ncreate index if not exists outcomes_market_id_idx on public.outcomes (market_id);\ncreate index if not exists wagers_user_id_idx on public.wagers (user_id);\ncreate index if not exists wagers_market_id_idx on public.wagers (market_id);\ncreate index if not exists wallet_transactions_user_id_idx on public.wallet_transactions (user_id);\n"
"\nDO \nBEGIN\n  ALTER PUBLICATION supabase_realtime ADD TABLE public.events;\nEXCEPTION\n  WHEN duplicate_object THEN NULL;\nEND\n;\n\nDO \nBEGIN\n  ALTER PUBLICATION supabase_realtime ADD TABLE public.markets;\nEXCEPTION\n  WHEN duplicate_object THEN NULL;\nEND\n;\n\nDO \nBEGIN\n  ALTER PUBLICATION supabase_realtime ADD TABLE public.outcomes;\nEXCEPTION\n  WHEN duplicate_object THEN NULL;\nEND\n;\n\nDO \nBEGIN\n  ALTER PUBLICATION supabase_realtime ADD TABLE public.wallet_accounts;\nEXCEPTION\n  WHEN duplicate_object THEN NULL;\nEND\n;\n\nDO \nBEGIN\n  ALTER PUBLICATION supabase_realtime ADD TABLE public.wagers;\nEXCEPTION\n  WHEN duplicate_object THEN NULL;\nEND\n;\n\nDO \nBEGIN\n  ALTER PUBLICATION supabase_realtime ADD TABLE public.wallet_transactions;\nEXCEPTION\n  WHEN duplicate_object THEN NULL;\nEND\n;\n"
